import mongoose from "mongoose";
import { RUN_CUT_STATUSES } from "../utils/hours.js";
import { DISRUPTION_TYPES } from "../utils/disruptionTypes.js";

const runCutDaySchema = new mongoose.Schema(
  {
    division: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Division",
      required: true,
    },
    route: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Route",
      required: true,
    },
    date: {
      type: Date,
      required: true,
    },
    operator: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Operator",
      default: null,
    },
    vehicle: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Vehicle",
      default: null,
    },
    pulloutAddress: {
      type: String,
      trim: true,
      default: "",
    },
    startTime: {
      type: String,
      default: null,
    },
    endTime: {
      type: String,
      default: null,
    },
    status: {
      type: String,
      enum: RUN_CUT_STATUSES,
      default: "active",
    },
    serviceHours: {
      type: Number,
      default: 0,
    },
    revenueHours: {
      type: Number,
      default: 0,
    },
    clientNotes: {
      type: String,
      trim: true,
      default: "",
    },
    disruptionType: {
      type: String,
      enum: [...DISRUPTION_TYPES, null],
      default: null,
    },
    disruptionNotes: {
      type: String,
      trim: true,
      default: "",
    },
    deployed: {
      type: Boolean,
      default: false,
    },
    // Which actual route a deployed standby is covering that day — only
    // meaningful when deployed is true and this route itself is a standby
    // route; cleared whenever deployed is set back to false.
    coveringRoute: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Route",
      default: null,
    },
    // A one-off duty Deployment added for this date only (an operator
    // picking up extra revenue on a route that isn't normally scheduled
    // that day) — never generated by the persistent RunCut projection, and
    // protected from its cleanup pass so it isn't swept away as "no longer
    // scheduled."
    isExtra: {
      type: Boolean,
      default: false,
    },
    // Marks fields Deployment has overridden for this specific date, so the
    // daily projection from the persistent RunCut assignment leaves them
    // alone instead of overwriting them — a Deployment-side exception
    // applies to this day only, never the ongoing schedule.
    overrides: {
      status: { type: Boolean, default: false },
      clientNotes: { type: Boolean, default: false },
      disruption: { type: Boolean, default: false },
    },
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
  },
  { timestamps: true }
);

runCutDaySchema.index({ division: 1, route: 1, date: 1 }, { unique: true });
runCutDaySchema.index({ division: 1, date: 1 });

const RunCutDay = mongoose.model("RunCutDay", runCutDaySchema);

export default RunCutDay;
